// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	SpotifyID string `json:"spotifyID"`
}

type User struct {
	ID        string `json:"id"`
	SpotifyID string `json:"spotifyID"`
	Name      string `json:"name"`
}
